#!/usr/bin/env python3
"""Inject a managed "Resource Notes" backlink section into the existing Topic MOC
and Learning Path notes, so the Obsidian graph is navigable in both directions.

The section is delimited by HTML comment markers and is fully regenerated on each
run — everything outside the markers (your curated content) is preserved untouched.

A note is listed under a MOC when the MOC's topic is the note's primary_topic or
one of its secondary_topics. Learning Path notes list only primary-topic matches.

Run:
  python3 link_mocs.py \
      --inventory ".../resource_inventory_enriched.jsonl" \
      --generated-dir ".../Generated" \
      --notes-subdir "Resource Notes"
"""
import argparse
import json
import os
import re

BEGIN = "<!-- BEGIN resource-notes (auto-generated by link_mocs.py) -->"
END = "<!-- END resource-notes (auto-generated by link_mocs.py) -->"
SKILL_ORDER = {"beginner": 0, "intermediate": 1, "advanced": 2}


def split_list(value):
    if not value:
        return []
    return [p.strip() for p in re.split(r"[;,]", value) if p.strip()]


def norm_moc(topic):
    return "Topic MOC - " + topic.replace("&", "and").replace("/", "-").strip()


def norm_lp(topic):
    return "Learning Path - " + topic.replace("/", "-").strip()


def safe_stem(file_name):
    return re.sub(r'[\\/:*?"<>|]', "_", os.path.splitext(file_name)[0])


def load_inventory(path):
    recs = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                recs.append(json.loads(line))
    return recs


def build_block(entries):
    """entries: list of (skill, title, note_stem, is_primary)."""
    by_skill = {}
    for skill, title, stem, primary in entries:
        by_skill.setdefault(skill or "unspecified", []).append((title, stem, primary))
    lines = [BEGIN, "", f"## 📑 Resource Notes ({len(entries)})", ""]
    for skill in sorted(by_skill, key=lambda s: SKILL_ORDER.get(s, 99)):
        items = sorted(by_skill[skill], key=lambda x: x[0].lower())
        lines.append(f"**{skill.capitalize()}**")
        lines.append("")
        for title, stem, primary in items:
            star = "" if primary else " ·  _(secondary)_"
            lines.append(f"- [[{stem}|{title}]]{star}")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def inject(path, block):
    with open(path, encoding="utf-8") as f:
        content = f.read()
    if BEGIN in content and END in content:
        new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block,
                     content, flags=re.S)
    else:
        new = content.rstrip() + "\n\n" + block + "\n"
    if new != content:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new)
        return True
    return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", required=True)
    ap.add_argument("--generated-dir", required=True)
    ap.add_argument("--notes-subdir", default="Resource Notes")
    args = ap.parse_args()

    recs = load_inventory(args.inventory)
    notes_dir = os.path.join(args.generated_dir, args.notes_subdir)
    have_note = set()
    if os.path.isdir(notes_dir):
        have_note = {fn[:-3] for fn in os.listdir(notes_dir) if fn.endswith(".md")}

    moc_entries = {}   # moc/lp note name -> list of entries
    for r in recs:
        stem = safe_stem(r["file_name"])
        if stem not in have_note:
            continue
        title = r.get("title") or stem
        skill = (r.get("skill_level") or "").lower()
        primary = r.get("primary_topic") or ""
        secondary = split_list(r.get("secondary_topics"))

        if primary:
            moc_entries.setdefault(norm_moc(primary), []).append((skill, title, stem, True))
            moc_entries.setdefault(norm_lp(primary), []).append((skill, title, stem, True))
        for t in secondary:
            moc_entries.setdefault(norm_moc(t), []).append((skill, title, stem, False))

    updated = 0
    for note_name, entries in sorted(moc_entries.items()):
        path = os.path.join(args.generated_dir, note_name + ".md")
        if not os.path.isfile(path):
            continue  # only inject into MOC/LP notes that actually exist
        # de-dup entries by stem (a note could match a topic twice)
        seen, uniq = set(), []
        for e in entries:
            if e[2] not in seen:
                seen.add(e[2])
                uniq.append(e)
        if inject(path, build_block(uniq)):
            updated += 1
            print(f"  + {note_name}  ({len(uniq)} notes)")

    print(f"Updated {updated} MOC / Learning Path note(s).")


if __name__ == "__main__":
    main()
